theme: jekyll-theme-cayman
title: "Heat Controller App"
description: "Инструкция по работе с приложением Heat Controller App"

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "instruction"